# Site settings
title: 戴超的技术博客
email: dai965524749@gmail.com
description: > #戴超的技术博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jifengchao.github.io/" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: DCLOVEHYL
github_username:  jifengchao

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 戴超
  email: dai965524749@gmail.com
  link: https://jifengchao.github.io/
  weibo: http://weibo.com/p/1005052834143574
  github: https://github.com/jifengchao
title: 戴超的技术博客                             #自定义常量

# avatar头像及Favicon
avatar: https://avatars3.githubusercontent.com/u/12393581?v=4&u=36096dcb82679ee5e70adb6c581473415af785ef&s=400
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:
  src: //hm.baidu.com/hm.js?22d94317cfb9f9e0bb476228d9f79278

# disqus 设置
disqus:
  shortname: jifengchao